services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - pgadmin4
    links:
      - 'postgres:postgres'
  postgres:
    image: 'postgres:latest'
    restart: 'always'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  pgadmin4:
    image: 'dpage/pgadmin4'
    restart: 'always'
    user: 'root'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=cback@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=password'
      - 'PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False'
      - 'PGADMIN_CONFIG_SERVER_MODE=False'
    ports:
      - '5050:80'
    depends_on:
      - 'postgres'
    links:
      - 'postgres:postgres'
    volumes: # doesn't really work right now... maybe fix in the future
      - './servers.json:/pgadmin4/servers.json'
      - './pgpass:/pgpass'

  frontend:
    build:
      context: ./ams-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"